version: "3.7"

services:
  mysql:
    user: "${HOST_USER_ID}:${HOST_USER_GID}"
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=${SUBSCRIPTION_DB_NAME}
      - MYSQL_USER=${SUBSCRIPTION_DB_USER}
      - MYSQL_PASSWORD=${SUBSCRIPTION_DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3307:3307"
    volumes:
      - ./mysql/storage:/var/lib/mysql
  php-fpm:
    user: "${HOST_USER_ID}:${HOST_USER_GID}"
    build:
      context: ./php-fpm
    depends_on:
      - mysql
    volumes:
      - ../../:/var/www
    links:
      - memcached
  memcached:
    image: memcached:1.6.9
    entrypoint: /entrypoint.sh -m 128
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "8080:8080"
