<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20210519105120 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create `currencyRate` table';
    }

    public function up(Schema $schema): void
    {
        $this->connection->executeQuery("
            CREATE TABLE `currencyRate` (
                `rateDate` date NOT NULL,
                `currencyFrom` enum(
                    'AED','AFN','ALL','AMD','ANG','AOA','ARS','AUD','AWG','AZN','BAM','BBD','BDT','BGN','BHD','BIF',
                    'BMD','BND','BOB','BOV','BRL','BSD','BTN','BWP','BYR','BZD','CAD','CDF','CHE','CHF','CHW','CLF',
                    'CLP','CNY','COP','COU','CRC','CUC','CUP','CVE','CZK','DJF','DKK','DOP','DZD','EGP','ERN','ETB',
                    'EUR','FJD','FKP','GBP','GEL','GHS','GIP','GMD','GNF','GTQ','GYD','HKD','HNL','HRK','HTG','HUF',
                    'IDR','ILS','INR','IQD','IRR','ISK','JMD','JOD','JPY','KES','KGS','KHR','KMF','KPW','KRW','KWD',
                    'KYD','KZT','LAK','LBP','LKR','LRD','LSL','LYD','MAD','MDL','MGA','MKD','MMK','MNT','MOP','MRO',
                    'MUR','MVR','MWK','MXN','MXV','MYR','MZN','NAD','NGN','NIO','NOK','NPR','NZD','OMR','PAB','PEN',
                    'PGK','PHP','PKR','PLN','PYG','QAR','RON','RSD','RUB','RWF','SAR','SBD','SCR','SDG','SEK','SGD',
                    'SHP','SLL','SOS','SRD','SSP','STD','SVC','SYP','SZL','THB','TJS','TMT','TND','TOP','TRY','TTD',
                    'TWD','TZS','UAH','UGX','USD','USN','UYI','UYU','UZS','VEF','VND','VUV','WST','XAF','XCD','XOF',
                    'XPF','YER','ZAR','ZMW','ZWL'
                ) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                `rateToAED` float NOT NULL DEFAULT '0',
                `rateToAFN` float NOT NULL DEFAULT '0',
                `rateToALL` float NOT NULL DEFAULT '0',
                `rateToAMD` float NOT NULL DEFAULT '0',
                `rateToANG` float NOT NULL DEFAULT '0',
                `rateToAOA` float NOT NULL DEFAULT '0',
                `rateToARS` float NOT NULL DEFAULT '0',
                `rateToAUD` float NOT NULL DEFAULT '0',
                `rateToAWG` float NOT NULL DEFAULT '0',
                `rateToAZN` float NOT NULL DEFAULT '0',
                `rateToBAM` float NOT NULL DEFAULT '0',
                `rateToBBD` float NOT NULL DEFAULT '0',
                `rateToBDT` float NOT NULL DEFAULT '0',
                `rateToBGN` float NOT NULL DEFAULT '0',
                `rateToBHD` float NOT NULL DEFAULT '0',
                `rateToBIF` float NOT NULL DEFAULT '0',
                `rateToBMD` float NOT NULL DEFAULT '0',
                `rateToBND` float NOT NULL DEFAULT '0',
                `rateToBOB` float NOT NULL DEFAULT '0',
                `rateToBOV` float NOT NULL DEFAULT '0',
                `rateToBRL` float NOT NULL DEFAULT '0',
                `rateToBSD` float NOT NULL DEFAULT '0',
                `rateToBTN` float NOT NULL DEFAULT '0',
                `rateToBWP` float NOT NULL DEFAULT '0',
                `rateToBYR` float NOT NULL DEFAULT '0',
                `rateToBZD` float NOT NULL DEFAULT '0',
                `rateToCAD` float NOT NULL DEFAULT '0',
                `rateToCDF` float NOT NULL DEFAULT '0',
                `rateToCHE` float NOT NULL DEFAULT '0',
                `rateToCHF` float NOT NULL DEFAULT '0',
                `rateToCHW` float NOT NULL DEFAULT '0',
                `rateToCLF` float NOT NULL DEFAULT '0',
                `rateToCLP` float NOT NULL DEFAULT '0',
                `rateToCNY` float NOT NULL DEFAULT '0',
                `rateToCOP` float NOT NULL DEFAULT '0',
                `rateToCOU` float NOT NULL DEFAULT '0',
                `rateToCRC` float NOT NULL DEFAULT '0',
                `rateToCUC` float NOT NULL DEFAULT '0',
                `rateToCUP` float NOT NULL DEFAULT '0',
                `rateToCVE` float NOT NULL DEFAULT '0',
                `rateToCZK` float NOT NULL DEFAULT '0',
                `rateToDJF` float NOT NULL DEFAULT '0',
                `rateToDKK` float NOT NULL DEFAULT '0',
                `rateToDOP` float NOT NULL DEFAULT '0',
                `rateToDZD` float NOT NULL DEFAULT '0',
                `rateToEGP` float NOT NULL DEFAULT '0',
                `rateToERN` float NOT NULL DEFAULT '0',
                `rateToETB` float NOT NULL DEFAULT '0',
                `rateToEUR` float NOT NULL DEFAULT '0',
                `rateToFJD` float NOT NULL DEFAULT '0',
                `rateToFKP` float NOT NULL DEFAULT '0',
                `rateToGBP` float NOT NULL DEFAULT '0',
                `rateToGEL` float NOT NULL DEFAULT '0',
                `rateToGHS` float NOT NULL DEFAULT '0',
                `rateToGIP` float NOT NULL DEFAULT '0',
                `rateToGMD` float NOT NULL DEFAULT '0',
                `rateToGNF` float NOT NULL DEFAULT '0',
                `rateToGTQ` float NOT NULL DEFAULT '0',
                `rateToGYD` float NOT NULL DEFAULT '0',
                `rateToHKD` float NOT NULL DEFAULT '0',
                `rateToHNL` float NOT NULL DEFAULT '0',
                `rateToHRK` float NOT NULL DEFAULT '0',
                `rateToHTG` float NOT NULL DEFAULT '0',
                `rateToHUF` float NOT NULL DEFAULT '0',
                `rateToIDR` float NOT NULL DEFAULT '0',
                `rateToILS` float NOT NULL DEFAULT '0',
                `rateToINR` float NOT NULL DEFAULT '0',
                `rateToIQD` float NOT NULL DEFAULT '0',
                `rateToIRR` float NOT NULL DEFAULT '0',
                `rateToISK` float NOT NULL DEFAULT '0',
                `rateToJMD` float NOT NULL DEFAULT '0',
                `rateToJOD` float NOT NULL DEFAULT '0',
                `rateToJPY` float NOT NULL DEFAULT '0',
                `rateToKES` float NOT NULL DEFAULT '0',
                `rateToKGS` float NOT NULL DEFAULT '0',
                `rateToKHR` float NOT NULL DEFAULT '0',
                `rateToKMF` float NOT NULL DEFAULT '0',
                `rateToKPW` float NOT NULL DEFAULT '0',
                `rateToKRW` float NOT NULL DEFAULT '0',
                `rateToKWD` float NOT NULL DEFAULT '0',
                `rateToKYD` float NOT NULL DEFAULT '0',
                `rateToKZT` float NOT NULL DEFAULT '0',
                `rateToLAK` float NOT NULL DEFAULT '0',
                `rateToLBP` float NOT NULL DEFAULT '0',
                `rateToLKR` float NOT NULL DEFAULT '0',
                `rateToLRD` float NOT NULL DEFAULT '0',
                `rateToLSL` float NOT NULL DEFAULT '0',
                `rateToLYD` float NOT NULL DEFAULT '0',
                `rateToMAD` float NOT NULL DEFAULT '0',
                `rateToMDL` float NOT NULL DEFAULT '0',
                `rateToMGA` float NOT NULL DEFAULT '0',
                `rateToMKD` float NOT NULL DEFAULT '0',
                `rateToMMK` float NOT NULL DEFAULT '0',
                `rateToMNT` float NOT NULL DEFAULT '0',
                `rateToMOP` float NOT NULL DEFAULT '0',
                `rateToMRO` float NOT NULL DEFAULT '0',
                `rateToMUR` float NOT NULL DEFAULT '0',
                `rateToMVR` float NOT NULL DEFAULT '0',
                `rateToMWK` float NOT NULL DEFAULT '0',
                `rateToMXN` float NOT NULL DEFAULT '0',
                `rateToMXV` float NOT NULL DEFAULT '0',
                `rateToMYR` float NOT NULL DEFAULT '0',
                `rateToMZN` float NOT NULL DEFAULT '0',
                `rateToNAD` float NOT NULL DEFAULT '0',
                `rateToNGN` float NOT NULL DEFAULT '0',
                `rateToNIO` float NOT NULL DEFAULT '0',
                `rateToNOK` float NOT NULL DEFAULT '0',
                `rateToNPR` float NOT NULL DEFAULT '0',
                `rateToNZD` float NOT NULL DEFAULT '0',
                `rateToOMR` float NOT NULL DEFAULT '0',
                `rateToPAB` float NOT NULL DEFAULT '0',
                `rateToPEN` float NOT NULL DEFAULT '0',
                `rateToPGK` float NOT NULL DEFAULT '0',
                `rateToPHP` float NOT NULL DEFAULT '0',
                `rateToPKR` float NOT NULL DEFAULT '0',
                `rateToPLN` float NOT NULL DEFAULT '0',
                `rateToPYG` float NOT NULL DEFAULT '0',
                `rateToQAR` float NOT NULL DEFAULT '0',
                `rateToRON` float NOT NULL DEFAULT '0',
                `rateToRSD` float NOT NULL DEFAULT '0',
                `rateToRUB` float NOT NULL DEFAULT '0',
                `rateToRWF` float NOT NULL DEFAULT '0',
                `rateToSAR` float NOT NULL DEFAULT '0',
                `rateToSBD` float NOT NULL DEFAULT '0',
                `rateToSCR` float NOT NULL DEFAULT '0',
                `rateToSDG` float NOT NULL DEFAULT '0',
                `rateToSEK` float NOT NULL DEFAULT '0',
                `rateToSGD` float NOT NULL DEFAULT '0',
                `rateToSHP` float NOT NULL DEFAULT '0',
                `rateToSLL` float NOT NULL DEFAULT '0',
                `rateToSOS` float NOT NULL DEFAULT '0',
                `rateToSRD` float NOT NULL DEFAULT '0',
                `rateToSSP` float NOT NULL DEFAULT '0',
                `rateToSTD` float NOT NULL DEFAULT '0',
                `rateToSVC` float NOT NULL DEFAULT '0',
                `rateToSYP` float NOT NULL DEFAULT '0',
                `rateToSZL` float NOT NULL DEFAULT '0',
                `rateToTHB` float NOT NULL DEFAULT '0',
                `rateToTJS` float NOT NULL DEFAULT '0',
                `rateToTMT` float NOT NULL DEFAULT '0',
                `rateToTND` float NOT NULL DEFAULT '0',
                `rateToTOP` float NOT NULL DEFAULT '0',
                `rateToTRY` float NOT NULL DEFAULT '0',
                `rateToTTD` float NOT NULL DEFAULT '0',
                `rateToTWD` float NOT NULL DEFAULT '0',
                `rateToTZS` float NOT NULL DEFAULT '0',
                `rateToUAH` float NOT NULL DEFAULT '0',
                `rateToUGX` float NOT NULL DEFAULT '0',
                `rateToUSD` float NOT NULL DEFAULT '0',
                `rateToUSN` float NOT NULL DEFAULT '0',
                `rateToUYI` float NOT NULL DEFAULT '0',
                `rateToUYU` float NOT NULL DEFAULT '0',
                `rateToUZS` float NOT NULL DEFAULT '0',
                `rateToVEF` float NOT NULL DEFAULT '0',
                `rateToVND` float NOT NULL DEFAULT '0',
                `rateToVUV` float NOT NULL DEFAULT '0',
                `rateToWST` float NOT NULL DEFAULT '0',
                `rateToXAF` float NOT NULL DEFAULT '0',
                `rateToXCD` float NOT NULL DEFAULT '0',
                `rateToXOF` float NOT NULL DEFAULT '0',
                `rateToXPF` float NOT NULL DEFAULT '0',
                `rateToYER` float NOT NULL DEFAULT '0',
                `rateToZAR` float NOT NULL DEFAULT '0',
                `rateToZMW` float NOT NULL DEFAULT '0',
                `rateToZWL` float NOT NULL DEFAULT '0',
                PRIMARY KEY (`rateDate`,`currencyFrom`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
        ");
    }

    public function down(Schema $schema): void
    {
        $this->connection->executeQuery("DROP TABLE IF EXISTS `currencyRate`");
    }
}
