services:
  _defaults:
    autowire: true
    autoconfigure: true

  KiloHealth\:
    resource: '../src'
    exclude:
      - '../src/Subscription/Ui/DependencyInjection/'
      - '../src/Subscription/Ui/Kernel.php'
      - '../src/Subscription/Domain/ValueObject/'

  KiloHealth\Subscription\Ui\Http\:
    resource: '../src/Subscription/Ui/Http/'
    tags: ['controller.service_arguments']

  KiloHealth\Subscription\Infrastructure\Persistence\DB\SubscriptionRepository:
    arguments:
      $connection: '@doctrine.dbal.subscription_connection'

  KiloHealth\Subscription\Domain\Repository\SubscriptionRepositoryInterface:
    public: true
    alias: KiloHealth\Subscription\Infrastructure\Persistence\DB\SubscriptionRepository

  KiloHealth\Subscription\Infrastructure\Persistence\DB\TransactionRepository:
    arguments:
      $connection: '@doctrine.dbal.subscription_connection'

  KiloHealth\Subscription\Domain\Repository\TransactionRepository:
    public: true
    alias: KiloHealth\Subscription\Infrastructure\Persistence\DB\TransactionRepository
